notifications:
  email:
    on_success: never
    on_failure: always
matrix:
  include:
    - os: linux
      language: python
      python:
        - "3.8"
      install:
        - pip install pylint
        - pip install coveralls
        - pip install sphinx sphinx-rtd-theme
        - pip install .
      after_success:
        - coveralls
    - os: osx
      osx_image: xcode10.2
      language: shell
      install:
        - sudo python3 -m pip install pylint
        - sudo python3 -m pip install coverage
        - sudo python3 -m pip install nose
        - sudo python3 -m pip install sphinx sphinx-rtd-theme
        - sudo python3 -m pip install .
    - os: windows
      language: sh
      before_install:
        - choco install python --version=3.8.3
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install pylint
        - pip install coverage
        - pip install nose
        - pip install sphinx sphinx-rtd-theme
        - pip install .
script:
  - pylint mr4mp
  - nosetests
  - cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../setup.py && make html
