name: lint-test-cover-docs
on:
  push
jobs:
  lint_test_docs:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9']
    name: "Python ${{ matrix.python-version }}"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Lint and test module.
        run: |
          pip install -U pylint coverage nose .
          python -m pylint mr4mp # Check against linting rules.
          python -m nose --cover-erase # Test using nose.
      - name: Test auto-generation of documentation.
        run: |
          pip install -U -r docs/requirements.txt
          cd docs && sphinx-apidoc -f -E --templatedir=_templates -o _source .. ../setup.py && make html && cd ..
  cover:
    runs-on: ubuntu-latest
    name: "Python 3.8 for Coveralls"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python.
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          architecture: x64
      - name: Generate and publish coverage.
        run: |
          pip install -U pylint coveralls nose .
          python -m nose --cover-erase # Generate coverage report.
          python -m coveralls --service=github # Submit to coveralls.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
